[package]
name = "dwallet-mpc"
edition = "2021"
version.workspace = true

[dependencies]
proof = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "proof", rev="517ff6d696ff9943c" }
maurer = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "maurer" , rev="517ff6d696ff9943c"}
group = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "group", rev="517ff6d696ff9943c" }
tiresias = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "tiresias", rev="517ff6d696ff9943c" }
mpc = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "mpc", features = ["parallel"] , rev="517ff6d696ff9943c" }
twopc_mpc = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "2pc-mpc", features = ["secp256k1", "bulletproofs", "paillier", "class_groups", "benchmarking"], rev="517ff6d696ff9943c" }
pera-core.workspace = true
anyhow.workspace = true
bcs.workspace = true
rand_core = "0.6.4"

[lints]
workspace = true
