[package]
name = "dwallet-mpc"
edition = "2021"
version.workspace = true

[dependencies]
proof = { path = "../../../cryptography-private/proof" }
maurer = { path = "../../../cryptography-private/maurer" }
group = { path = "../../../cryptography-private/group"}
mpc = { path = "../../../cryptography-private/mpc" }
tiresias = { path = "../../../cryptography-private/tiresias"}
twopc_mpc = { path = "../../../cryptography-private/2pc-mpc", features = ["secp256k1", "bulletproofs", "paillier", "without-benchmarks"] }
anyhow.workspace = true
bcs.workspace = true
rand_core = "0.6.4"

[lints]
workspace = true
